version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udv-bff-app
    restart: always
    image: udv-app:v1.0.0
    ports:
      - "${PORT}:3000"
    environment:
      PORT: ${PORT}
      PG_HOST: udv-backend-postgres
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: udv-postgres
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    hostname: ${PG_HOST}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_USER} -d ${PG_DATABASE} -h ${PG_HOST} -p ${PG_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
